INSERT INTO user (expiry_date, name, password) VALUES ('2018-05-13', 'Toni', 'Test')
INSERT INTO user (expiry_date, name, password) VALUES ('2018-05-13', 'Toni2', 'Test2')
INSERT INTO addiction (name, description) VALUES('Alcoholism', 'Alcoholism, also known as alcohol use disorder (AUD), is a broad term for any drinking of alcohol that results in mental or physical health problems. The disorder was previously divided into two types: alcohol abuse and alcohol dependence. In a medical context, alcoholism is said to exist when two or more of the following conditions is present: a person drinks large amounts over a long time period, has difficulty cutting down, acquiring and drinking alcohol takes up a great deal of time, alcohol is strongly desired, usage results in not fulfilling responsibilities, usage results in social problems, usage results in health problems, usage results in risky situations, withdrawal occurs when stopping, and alcohol tolerance has occurred with use.')
INSERT INTO addiction (name, description) VALUES('Cocaine Dependence', 'Cocaine dependence is a psychological desire to use cocaine regularly. Cocaine overdose may result in cardiovascular and brain damage, such as: constricting blood vessels in the brain, causing strokes and constricting arteries in the heart; causing heart attacks. The use of cocaine creates euphoria and high amounts of energy. If taken in large, unsafe doses, it is possible to cause mood swings, paranoia, insomnia, psychosis, high blood pressure, a fast heart rate, panic attacks, cognitive impairments and drastic changes in personality.')
INSERT INTO addiction (name, description) VALUES('Problem Gambling', 'Problem gambling (or ludomania, but usually referred to as "gambling addiction" or "compulsive gambling") is an urge to gamble continuously despite harmful negative consequences or a desire to stop.')
INSERT INTO symptom (description, addiction_id) VALUES ('Drinks large amounts over a long period', 1)
INSERT INTO symptom (description, addiction_id) VALUES ('Difficulty cutting down', 1)
INSERT INTO symptom (description, addiction_id) VALUES ('Acquiring and drinking alcohol takes up a lot of time', 1)
INSERT INTO symptom (description, addiction_id) VALUES ('Usage results in problems', 1)
INSERT INTO symptom (description, addiction_id) VALUES ('Withdrawal occurs when stopping', 1)
INSERT INTO symptom (description, addiction_id) VALUES ('Alcohol tolerance has occurred', 1)
INSERT INTO symptom (description, addiction_id) VALUES ('Aggression', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Severe paranoia', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Restlessness', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Confusion', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Tactile hallucinations', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Suicide thoughts', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Unusal weith loss', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Trouble maintaining relationships', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Unhealthy pale appearance', 2)
INSERT INTO symptom (description, addiction_id) VALUES ('Need to gamble with increasing amounts of money in order to achieve the desired excitement', 3)
INSERT INTO symptom (description, addiction_id) VALUES ('Restless or irritable when attempting to cut down or stop gambling', 3)
INSERT INTO symptom (description, addiction_id) VALUES ('Repeated unsuccessful efforts to control, cut back, or stop gambling', 3)
INSERT INTO symptom (description, addiction_id) VALUES ('Often preoccupied with gambling', 3)
INSERT INTO symptom (description, addiction_id) VALUES ('Gambling when feeling distressed', 3)
INSERT INTO symptom (description, addiction_id) VALUES ('Lying to conceal the extent of involvement with gambling', 3)
INSERT INTO symptom (description, addiction_id) VALUES ('Jeopardize or loss a significant relationship, job, education or career opportunity because of gambling', 3)
INSERT INTO symptom (description, addiction_id) VALUES ('Relying on others to provide money to relieve desperate financial situations caused by gambling', 3)
